baseURL = "sino-cdrc.github.io"
title = "CRI@ÉCPKN"


paginate = 11
copyright = "&copy;2021 <a href=\"https://sino.github.io/\">CRI@ÉCPKN</a> All rights reserved. | <a href=\"http://creativecommons.org/licenses/by-nc/4.0/\">CC BY-NC 4.0</a> | "
enableEmoji = true
enableGitInfo = false
summaryLength = 75
disablePathToLower = true

defaultContentLanguage = "zh"
hasCJKLanguage = true
defaultContentLanguageInSubdir = false

# googleAnalytics = "UA-123-45"

[markup]
  [markup.highlight]
    codeFences = false
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "colorful"
    tabWidth = 4
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false
  [markup.goldmark.renderer]
    unsafe = true

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"
  author = "authors"

[build]
  useResourceCacheWhen = "always"

